import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Navbar from "../components/Navbar.jsx";
import Footer from '../components/Footer';
import {useEffect} from "react";
import {handleCursorHoverButtons, handleCursorOutButtons} from "../components/actions.js"

export default function Home() {

  return (
    <div className={styles.home}>
      <Head>
        <title>Tudor Alexandru | An Enthusiastic Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{alignSelf: "start"}}>
        <Navbar />
      </div>

      <div className={styles.middle}>
            <div className={styles.tringle} onMouseEnter={handleCursorHoverButtons} onMouseLeave={handleCursorOutButtons}>
              <img src="/tringle.png" />
              <p>personal<br/>projects</p>
            </div>

            <div className={styles.text}>
              I create beautiful<br/> websites with my hands<br/> and a computer
            </div>

            <div className={styles.x} onMouseEnter={handleCursorHoverButtons} onMouseLeave={handleCursorOutButtons}>
              <img src="/x.png" />
              <p>case<br/>studies</p>
            </div>

      </div>

      <div style={{alignSelf: "end"}}>
        <Footer/>
      </div>

    </div>
  )
}
